name: incredibleman
version: 1.1.3+14
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  badges: ^2.0.1
  google_fonts: ^3.0.1
  flutter_secure_storage: ^5.0.2
  shimmer: ^2.0.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  share_plus: ^4.0.10
  url_launcher: ^6.1.5
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.0
  flutter_local_notifications: ^9.6.1
  firebase_messaging: ^11.4.4
  firebase_core: ^1.19.0
  firebase_auth: ^3.4.1
  google_sign_in: ^5.3.3
  pin_code_fields: ^7.4.0
  razorpay_flutter: ^1.3.2
  new_version: ^0.3.1
  lottie: ^1.3.0
  animated_splash_screen: ^1.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_foreground: "assets/icon/logo.png"
  adaptive_icon_background: "#141414"
  
flutter: 
  uses-material-design: true

  assets:
    - assets/images/